const Constant = {
  token: 'token',
  refreshToken: 'refreshToken',
  pageNumber: 'pageNumber',
  defaultErrorMessage: "Something went wrong, please try again!",
  whiteSpaceError: "Space cannot be entered",
  loginErrorMessage: "Please enter valid credentials",
  unAuthorizedError: "You are not authorized to access this website",
  emailRequiredValidationError: "Please enter the email address",
  emailValidationError:
    "Please enter a valid email address not more than 50 characters",
  phoneNumberValidationError: "Please enter a valid phone number.",
  minEmailLengthError: "Email cannot be less than 3 characters",
  maxEmailLengthError: "Email cannot be greater than 50 characters",
  credentialRequiredValidationError: "Please enter your credential",
  minPasswordLengthError: "Password cannot be less than 6 characters",
  maxPasswordLengthError: "Password cannot be greater than 20 characters",
  maxLengthOfMessageError: "Message cannot be greater than 250 characters",
  maxLengthOfVersionError: "Version cannot be greater than 20 characters",
  scoreOverlap: "Score must not be overlap",
  scoreMaxValueError:
    "The maximum score for score criteria must be greater than or equal to ",
  scoreMinValueError: "The minimum score for score criteria must be 0",
  scoreGapError: "Please correct the score gap between the score criterias",

  logPeoplIdRequiredError: "Please choose an ID",
  logThresholdTempErrorinFahrenheit:
    "Please provide a valid temperature from 91.4 to 111.2",
  logThresholdTempErrorinCelcius:
    "Please provide a valid temperature from 33 to 44",
  logDateTimeRequiredError: "Please choose a time",
  notificationReminderRequiredError:
    "Please provide a notification reminder time",
  desktopNotificationCountRequiredError:
    "Please provide a desktop notification count",

  userNameError: "Please enter valid name of maximum length 20",
  userAccessError: "At least one user access is required",
  valueError: "Please enter valid key of maximum length 30",
  keyError: "Please enter valid value of maximum length 30",
  notificationReminderError:
    "Please provide a valid notification reminder time",
  desktopNotificationCountError:
    "Please provide a valid desktop notification count",
  tempReadTimeoutError: "Please provide a valid timeout for temperature scan",
  heartbeatFrequencyError: "Please provide a valid heartbeat frequency",
  appStandbyTimeOurError: "Please provide a valid standby time in seconds",
  notificationSleepError: "Please provide a valid notification sleep time",
  appStandbyTimeOurRequiredError: "Please provide a standby time",
  notificationSleepRequiredError: "Please provide a notification sleep time",
  tempReadTimeoutRequiredError: "Please provide a timeout for temperature scan",
  heartbetFrequencyRequiredError: "Please provide a heartbeat frequency",
  addressError: "Please enter a valid address of maximum length 100",
  institutionNameError:
    "Please enter a valid institution name of maximum length 50",
  peopleTypeError: "Please enter a valid group type of maximum length 20",
  screenshotFrequencyRequiredError: "Please enter a screenshot frequency",
  screenshotFrequencyError: "Please enter a valid screenshot frequency",
  screenshotWidthRequiredError: "Please enter a screenshot width",
  screenshotWidthError: "Please enter a valid screenshot width",
  timeZoneRequiredError: "Please enter a time zone",
  welcomeMessageRequired: "Please enter a welcome message",
  accessKeyRequired: "Please enter access key",
  secretKeyRequired: "Please enter secret key",
  bucketRequired: "Please enter bucket",
  regionRequired: "Please enter region",
  duplicateTemplateError: "User template and survey template cannot be same!",
  positiveIntegerValidation: "It should be a positive integer or zero",
  missingScoreTo: "Score To Required",
  missingScoreFrom: "Score From Required",
  missingProfile: "Profile Required",
  scoreToValidation: "Must be greater than Score From",
  scoreFromValidation: "Must be less than Score To",
  profileDuplicateValidation: "Duplicate profile not allowed",
  valueDuplicateValidation: "Duplicate options not allowed",
  valueOptionError: "Option is required",
  questionShortNameError: "Length should be between 2 and 20",
  profileReportType: "Please pick an item!",
  inputTypeError: "Please select an input type",
  headingLengthError: "Ente a valid heading of maximum length 50",
  placeholderLengthError: "Enter a placeholder of maximum length 60",

  machineUserNameError: "Please enter a valid user name",
  macAddressError: "Please enter a valid mac address",
  templateError: "Please enter a valid template",
  QuestionShortNameError:
    " Enter a valid one word name which contain alphabets only",
  emailBodyError: "Please enter a body for the email",
  profileError: "Please enter a valid profile",
  templateNameError: "Please enter a valid template name",
  questionTitleValidation: "Please enter a question",
  profileNameError: "Please enter a valid profile name",
  surveyNameError: "Please enter a valid survey name",
  customerNameError: "Please enter a valid customer name",
  companyNameError: "Please enter a valid company name",
  projectNameError: "Please enter a valid project name",
  projectCodeError: "Please enter a valid project code",
  endDateError: "Please enter a valid date",
  remarkError: "Please enter a valid remark",
  surveyUserNameError: "Please enter a valid user name",
  welcomePageContentError: "Please enter the welcome page content",
  surveyKeyError: "Please enter a valid survey key",
  ShowRoomNameError: "Please enter a valid Showroom Name",
  assignedUserError: "Please enter a valid name",
  DescriptionError: "Please enter a valid description",
  locationRequiredError: "Please select a valid location",
  TemplateRequiredError: "Please select a template.",
  projectNameRequiredError: "Please choose a project.",
  GenderRequiredError: "Please select a valid gender",
  PhoneRequiredError: "Please select a valid phone number",
  userNameLengthError: "Please enter a valid user name of maximum length 35",
  assignedNameLengthError:
    "Please enter a valid assigned name of maximum length 35",
  maxLengthOfSurveyNameError:
    "Please enter a valid survey name of maximum length 100",
  maxLengthOfSurveyKeyError:
    "Please enter a valid survey key of maximum length 8",
  maxLengthOfTemplateNameError:
    "Please enter a valid template name of maximum length 50",
  maxLengthOfProfileNameError:
    "Please enter a valid profile name of maximum length 50",
  AssetNameError: "Please enter a valid asset name of maximum length 35",
  DescriptionLengthError:
    "Please enter a valid description of maximum length 35",
  ShowRommNameLengthError:
    "Please enter a valid Showroom name of maximum length 17",
  showRoomNameError: "Please enter a valid showroon name",
  platformIdError: "Please enter a valid platform id",
  platformIdLengthError:
    "Please enter a valid platform id of minimum length 3 and maximum length 10",
  assetTypeReqError: "Please choose an asset type",
  hotspotReqError: "Please choose a hotspot",
  posterReqError: "Please choose a poster",
  threeDModelReqError: "Please choose a 3D-Model",
  posterImagelReqError: "Please choose a Poster Image",
  assetsReqError: "Please choose an asset",
  customURLError: "Please enter a valid URL",
  customNameError: "Please enter a valid Custom name of maximum length 17",
  metaDataError: "Please enter a valid Metadata of maximum length 1024",
  subjectError: "Please enter a subject",
  msgFileError: "Only valid .pdf file of maximum size 8MB is allowed.",
  answerValidation: "Please select an answer",
  questionValidation: "Please select a question",
  surveyKeyLenghtValidation:
    "Please enter a valid surveykey with maximum length of 36",
  surveyKeyNotValid: "Alphabets, numbers, '_' and '-' are only allowed",
  maxLengthTextAreaError: "Please enter a sugeestion of maximum length 5000",
  maxValueError: "Please enter option of maximum length 200",
  maxQuestionLengthError: "Please enter question of maximum length 500",

  userAccess: {
    dashboard: 1,         //DashBoard
    archieved: 3,
    Voices: 4,
    users: 5,
    userRoles:6,
    institutionManagement: 999,
  },

  reportTypes: {
    profileReport: 1,
    detailReport: 2,
  },

  inputTypes: {
    radio: "radio",
    dropdown: "dropdown",
    big_text: "big_text"
  },

  reportTypesName: {
    1: "Profile Report",
    2: "Detailed Report",
  },

  inputTypeNames: {
    1: "Radio Type",
    2: "DropDown Type",
    3: "Textbox"
  },

  kiteRoles: {
    Management: "Management",
    Delivery_Head: "Delivery Head"
  },

  departmentName: {
    QA: "QA"
  },

  DetailReportProfileName: "Helpful Resources",

  itemsPerPage: 10,
  defaultPageNumber: 1,
  deleteModalTitle: "Warning",
  deleteModalContent: "Do you want to delete this record?",
  idRequiredValidationError: "Please provide a valid ID of maximum length 8",
  formValidationError: "Please provide valid parameters",
  resetPasswordWarning: "Are you sure you want to reset the password?",
  newPasswordRequiredError: "Enter your new password",
  confirmPasswordRequiredError: "Please confirm your password",
  credentialMatchError: "Credential do not match!",
  credentialValidationError:
    "Credential must contain at least one uppercase, one lower case, one numeral, one special character and have a minimum of 6 characters",
  fieldRequiredValidation: "Please provide your comment.",
  deleteAssetModalContent: "Are you sure to delete this?",
  publishAssetModalContent: "Are you sure to publish this?",
  unpublishAssetModalContent: "Are you sure to unpublish this?",

  appName: "Dyna Form",

  passwordMinLength: 6,
  passwordMaxLength: 20,
  emailMaxLength: 50,
  emailMinLength: 3,
  maxTemperature: 35,
  minValOfThresholdTempinCelcius: 33,
  maxValOfThresholdTempinCelcius: 44,
  minValOfThresholdTempinFahrenheit: 91.4,
  maxValOfThresholdTempinFahrenheit: 111.2,
  maxLengthOfPeopleId: 8,
  maxLengthOfName: 20,
  maxLengthOfRole: 20,
  notificationDuration: 3,
  maxLengthOfSchoolId: 6,
  maxLengthOfMessage: 250,
  maxLengthOfVersion: 20,
  maxLengthOfAdress: 100,
  maxLengthOfInstitutionName: 50,
  maxLengthOfLocation: 100,
  maxLengthOfAddress: 150,
  maxLengthOfUserName: 35,
  maxLengthOfAssignedName: 35,
  maxLengthOfMacAddress: 17,
  maxLengthOfTemplateName: 50,
  maxLengthOfProfileName: 50,
  maxLengthOfSurveyName: 100,
  maxLengthOfSurveyKey: 36,
  maxLengthOfDescription: 35,
  maxLengthOfShowRoomName: 17,
  minLengthOfPlatformId: 3,
  minLengthOfDisplayName: 3,
  maxLengthOfDisplayName: 20,
  maxLengthOfMetadata: 1024,
  maxLengthOfTextArea: 5000,
  maxFileSize: 4,
  minQuestionShortNameLength: 2,
  maxQuestionLength: 500,
  maxQuestionShortNameLength: 20,
  maxHeadingLength: 50,
  maxPlaceholderLength: 60,
  maxValueLength: 200,

  userRoleError: "Please enter a valid role of maximum length 20",
  roleRequired: "Please select a role",
  addValidPhoneNumber: "Please provide a valid phone number",
  addValidTemperature:
    "Please provide a valid temperature upto 2 decimal points",
  schoolIdEditWarning:
    "Changing this app config will make all the previous QR codes invalid. Are you sure you want to do this?",
  schoolIdError: "Please enter a valid ID of maximum length 6",
  locationError: "Please enter a location of maximum length 100",
  environmentError: "Please enter a name of environment",
  AddressError: "Please enter an address of maximum length 150",
  hotSpotCountError: "Please enter a valid count of hotspot",
  posterCountError: "Please enter a valid count of hotspot",
  inputTextValidation: "Please enter valid data of length 20",
  answerRequiredValidation: "Please choose atleast one option.",

  web: 1,
  mobile: 2,
  Kweb: "Web",
  Kmobile: "Mobile",
  androidVersionRequiredError: "Please enter your Android version",
  androidVersionError: "Please enter a valid Android version",
  appVersionRequiredError: "Please enter your App version",
  appVersionError: "Please enter a valid App version",
  macAppDownloadLinkError: "Please enter your Mac App download link",
  windowsAppDownloadLinkError: "Please enter your Windows App download link",
  linuxAppDownloadLinkError: "Please enter your Linux App download link",
  androidStoreLinkError: "Please enter your play store link",
  androidUpdateMessageError: "Please enter an Android update message",
  iosVersionRequiredError: "Please enter your iOS version",
  iosVersionError: "Please enter a valid iOS version",
  iosStoreLinkError: "Please enter your app store link",
  iosUpdateMessageError: "Please enter an iOS update message",
  privacyPolicyError: "Please enter privacy policy",
  legalDocumentVersionRequiredError: "Please enter the legal document version",
  privacyVersionError: "Please enter a valid privacy policy version",
  maxLengthOfPrivacyVersionError:
    "Please enter a valid privacy policy version of maximum length 20",
  legalLinkError: "Please enter the legal agreement link",
  credentialResendSuccess: "Credential has been sent to [email].",
  associate3DModel: "Associate Corresponsing 3D Model To The Showroom",
  editShowroom: "Edit Showroom Details",
  glbModelError: "Please add a GLB model",
  fbxModelError: "Please add a FBX model",
  lightFileError: "Please add a .env light file",

  imageFileTypes: ["image/png", "image/jpg", "image/jpeg"],
  docFileTypes: [
    "application/msword",
    "application/pdf",
    "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    "application/vnd.oasis.opendocument.text",
  ],

  typeOfReport: [
    { id: 1, name: "Basic Report" },
    { id: 2, name: "Question Based Report" },
  ],
};

export default Constant;
